spring.application.name=code

spring.datasource.url=jdbc:mysql://172.21.74.198/inventory?usessl=false
spring.datasource.username=root

spring.datasource.password=ZAlABHSlxyhnstYEROBHXpTC
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:Do1ocMSaqRKx5PFZhcYrIRwz@172.21.223.186/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

 
